  0%|          | 0/296377 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/mnt/petrelfs/liaoyusheng/projects/MING/ming/train/train_mem.py", line 13, in <module>
    train()
  File "/mnt/petrelfs/liaoyusheng/projects/MING/ming/train/train.py", line 583, in train
    trainer.train(resume_from_checkpoint=True)
  File "/mnt/petrelfs/liaoyusheng/projects/MING-MOE-DATA/transformers/src/transformers/trainer.py", line 1885, in train
    return inner_training_loop(
  File "/mnt/petrelfs/liaoyusheng/projects/MING-MOE-DATA/transformers/src/transformers/trainer.py", line 2197, in _inner_training_loop
    self._load_rng_state(resume_from_checkpoint)
  File "/mnt/petrelfs/liaoyusheng/projects/MING-MOE-DATA/transformers/src/transformers/trainer.py", line 2764, in _load_rng_state
    torch.cuda.random.set_rng_state_all(checkpoint_rng_state["cuda"])
  File "/mnt/petrelfs/liaoyusheng/miniconda3/envs/ming/lib/python3.10/site-packages/torch/cuda/random.py", line 84, in set_rng_state_all
    set_rng_state(state, i)
  File "/mnt/petrelfs/liaoyusheng/miniconda3/envs/ming/lib/python3.10/site-packages/torch/cuda/random.py", line 75, in set_rng_state
    _lazy_call(cb)
  File "/mnt/petrelfs/liaoyusheng/miniconda3/envs/ming/lib/python3.10/site-packages/torch/cuda/__init__.py", line 229, in _lazy_call
    callable()
  File "/mnt/petrelfs/liaoyusheng/miniconda3/envs/ming/lib/python3.10/site-packages/torch/cuda/random.py", line 73, in cb
    default_generator.set_state(new_state_copy)
RuntimeError: RNG state is wrong size